name: Add pull requests to projects

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  add-to-project:
    name: Add pull request to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/Hillel-DevOps-230720/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
